'use strict';

const CONSTANTS = {};

CONSTANTS.SERVER = {
	ONE: 1,
};

CONSTANTS.MAX_DEFAULT_VALUE = 100000000000;

CONSTANTS.ERROR_TYPES = {
	DATA_NOT_FOUND: 'DATA_NOT_FOUND',
	BAD_REQUEST: 'BAD_REQUEST',
	MONGO_EXCEPTION: 'MONGO_EXCEPTION',
	ALREADY_EXISTS: 'ALREADY_EXISTS',
	FORBIDDEN: 'FORBIDDEN',
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
	UNAUTHORIZED: 'UNAUTHORIZED',
	INVALID_MOVE: 'InvalidMove',
};

CONSTANTS.REFERRAL_CODE_LENGTH = 6;

CONSTANTS.SERVER_TYPES = {
	API: 'api',
	SOCKET: 'socket',
};

CONSTANTS.CHAINS = {
	ETH: 1,
	SOLANA: 2,
	BLAST: 3,
	BASE: 4
};

CONSTANTS.TRANSACTION_TYPES = {
	SELL: 1,
	BUY: 2,
	GIVEN_AWAY: 3
};

CONSTANTS.AD_STATUS = {
	PENDING: 1, // After content moderation, waiting for admin approval (not approved)
	REJECT: 2, // Rejected by admin
	APPROVED: 3 // Approved and active
};

CONSTANTS.USER_ROLES = {
	ADMIN: 1,
};

CONSTANTS.AVAILABLE_AUTHS = {
	ADMIN: 1,
	USER: 2,
	ADMIN_USER: 3
};

CONSTANTS.FILE_UPLOAD_TYPE = {
	PROFILE_IMAGE: 1,
};

CONSTANTS.TOKEN_TYPES = {
	LOGIN: 1,
	OTP: 2,
	RESET_PASSWORD: 3,
};

CONSTANTS.OTP_TYPES = {
	EMAIL_VERIFICATION: 1,
	FORGOT_PASSWORD: 2,
};

CONSTANTS.DATABASE_VERSIONS = {
	ONE: 1,
	TWO: 2,
	THREE: 3,
	FOUR: 4,
	FIVE: 5
};

CONSTANTS.USER_TYPE = {
	ADMIN: 1,
};

CONSTANTS.PASSWORD_PATTER_REGEX = /^(?=.{6,})(?=.*[a-z])(?=.*[0-9])(?=.*[A-Z])(?=.*[@#$%^&+=]).*$/;

CONSTANTS.NAME_REGEX = /^[a-zA-Z\s]{1,20}[a-zA-Z\s]$/;
CONSTANTS.PHONE_REGEX = /^\+\d{1,3}\d{8,10}$/;
CONSTANTS.ETHEREUM_ADDRESS_REGEX = /^0x[a-fA-F0-9]{40}$/;

CONSTANTS.NORMAL_PROJECTION = {
	__v: 0, isDeleted: 0, createdAt: 0, updatedAt: 0,
};

CONSTANTS.MESSAGES = require('./messages');

CONSTANTS.SECURITY = {
	JWT_SIGN_KEY: 'fasdkfjklandfkdsfjladsfodfafjalfadsfkads',
	BCRYPT_SALT: 8,
	STATIC_TOKEN_FOR_AUTHORIZATION: '58dde3df315587b279edc3f5eeb98145',
};
CONSTANTS.MAP_DEFAULT_MONGO_ID = '6298bbf1c5f9f220b1dd1de2';

CONSTANTS.LOGIN_TYPES = {
	METAMASK: 1,
};

CONSTANTS.OTP_LENGTH = 6;


CONSTANTS.EMAIL_TYPES = {
	WELCOME_EMAIL: 1,
	ICALENDER_EMAIL: 2,
	VERIFICATION_EMAIL: 3,
	FORGOT_PASSWORD_EMAIL: 4,
	RESET_PASSWORD_EMAIL: 5
};

CONSTANTS.EMAIL_SUBJECTS = {
	WELCOME_EMAIL: 'Test email',
	ICALENDER_EMAIL: 'Event calender',
	VERIFICATION_EMAIL: 'Verification email',
	FORGOT_PASSWORD_EMAIL: 'Forgot password email',
	RESET_PASSWORD_EMAIL: 'Reset Password',
};

CONSTANTS.EMAIL_CONTENTS = {
	WELCOME_EMAIL: '<p>Hello<span style=\'color: #3366ff;\'></span>,</p><p>This is test Email.</p><p>Regards,<br>Team CuesZ</p>',
	VERIFICATION_EMAIL: '',
	RESET_PASSWORD_EMAIL: 'public/templates/resetPasswordEmail.html',
	EMAIL_VERIFICATION_TEMPLATE: 'public/templates/verify-admin-email.html',
};


CONSTANTS.AVAILABLE_EXTENSIONS_FOR_FILE_UPLOADS = [ 'csv', 'png', 'jpeg', 'svg', 'jpg', 'mp4', 'x-m4v', 'webm', 'mov', 'svg', 'xls', 'xlsx', 'pdf' ];
CONSTANTS.ALLOWED_EXTENSIONS_FOR_PROFILE_IMAGE = [ 'jpg', 'png', 'jpeg', 'JPG', 'PNG', 'JPEG', 'webp', 'WEBP' ];

CONSTANTS.GENDER = {
	MALE: 'Male',
	FEMALE: 'Female',
	OTHERS: 'Other',
};

CONSTANTS.OTP_EXPIRIED_TIME_IN_SECONDS = 300;

CONSTANTS.OTP_EXPIRY_TIME = 5; // minutes

CONSTANTS.S3_DEFAULT_IMAGE = 'default.png';

CONSTANTS.REDIS_EXPIRE_TIME_IN_SEC = 10800;

CONSTANTS.SOCKET_EVENTS = {
	TEST: 'test',
	DISCONNECT: 'disconnect',
};

CONSTANTS.PAGINATION = {
	SKIP: 0,
	LIMIT: 10,
};

CONSTANTS.REDIS_EVENTS = {
	TEST: 'test',
};

CONSTANTS.CONTENT_TYPE = {
	HEADERS: 1,
	ETHEREUM_DESCRIPTIONS: 2,
	VIDEO_DETAILS: 3,
	PRIZE_SECTION: 4,
	WINNER_LIST: 5,
	WINNER_DETAILS: 6,
	CONTRACT_DETAILS: 7,
	ROADMAP: 8,
	FEATURED_DETAILS: 9,
	TOKEN_INFO: 10,
	EXTERNAL_AUDIT: 11,
	PREMIUM_MARKETPLACE: 12,
	FOOTERS: 13,
	AIRDROP: 14,
	PARTNERS: 15,
};

CONSTANTS.TX_TYPE = {
	BUY: 1,
	SELL: 2
};

CONSTANTS.TX_STATUS = {
	PENDING: 1,
	SUCCESS: 2,
	FAILURE: 3
};

CONSTANTS.USER_PRIZE_TYPE = {
	CAR: 1,
	TOKEN: 2
};
CONSTANTS.RESULT_TYPE = {
	MANUAL: 1,
	AUTOMATIC: 2
};

CONSTANTS.WINNER_PRIZE_UPDATE_TIME_LIMIT_DAYS = 7;

CONSTANTS.MATHEMATICAL = {
	MILLISECONDS_IN_A_DAY: 86400000 // 24 * 60 * 60 * 1000
};

CONSTANTS.SIGNATURE_MESSAGE = 'fasdkfjklandfkdsfjladsfodfafjalfadsfkads';

CONSTANTS.SEEDS = {
	MASTER: 'master'
};

CONSTANTS.DEFAULT_LOTTERY_START_VALUE = 10000000;

CONSTANTS.FILES_WITH_CUSTOM_CONTENT_TYPES = {
	'svg': 'image/svg+xml',
	'mp4': 'video/mp4',
	'webm': 'video/webm',
	'mov': 'video/quicktime',
};

CONSTANTS.COIN_FLIP_TYPE = {
	HEADS: 1,
	TAILS: 2
};

CONSTANTS.GAME_STATUS = {
	MATCH_MAKING_STARTED: 1,
	ON_GOING: 2,
	FINISHED: 3
};

CONSTANTS.TIMER_TYPE = {
	MATCH_MAKING_TIMER: 1,
	PLAYER_TURN: 2,
	APPLY_BET_TIMER: 3
};

module.exports = CONSTANTS;
